# Generated by Django 5.2.6 on 2026-08-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project'], name='expenses_ex_project_4e1d75_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expenses_ex_categor_fcaba7_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='expenses_ex_expense_cf8a73_idx'),
        ),
    ]
