# Generated by Django 5.2.6 on 2026-08-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-month', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee'], name='payroll_pay_employe_3f4ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['month'], name='payroll_pay_month_f3a16a_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payroll_pay_status_465a76_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'month'], name='payroll_pay_employe_f9e0ee_idx'),
        ),
    ]
